import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import GalleryImage1 from "../public/images/GalleryImage1.svg";
import GalleryImage2 from "../public/images/GalleryImage2.svg";
import GalleryImage3 from "../public/images/GalleryImage3.svg";
import Team1Img from "../public/images/Team1.svg";
import Team2Img from "../public/images/Team2.svg";
import Team3Img from "../public/images/Team3.svg";
import GalleryImage4 from "../public/images/GalleryImage4.svg";
import GalleryImage5 from "../public/images/GalleryImage5.svg";
import GalleryImage6 from "../public/images/GalleryImage6.svg";
import Header from "../components/Header";
import Footer from "../components/Footer";

export default function Home() {
	return (
		<div className="">
			<Head>
				<title>Tonic Technologies UI</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<div className="flex flex-col items-center bg-[#0A2640] pt-5 pb-44 px-[8%]" style={{}}>
				<span className="text-white pb-3 text-xl font-thin">About</span>
				<span className="text-white text-6xl font-thin text-center" style={{ lineHeight: 1.5 }}>
					We love to make great <br />
					things, things that matter.
				</span>
				<span className="text-white font-thin text-center mt-4">
					Funding handshake buyer business-to-business metrics iPad partnership. First mover advantage <br /> innovator success deployment
					non-disclosure.
				</span>
			</div>

			<div className="w-full relative h-[400px]">
				<div className="flex w-full px-[10%] mt-5 md:mt-0 flex-col md:flex-row sm:px-[12%] md:gap-14 md:h-[400px] lg:h-[600px] absolute left-0 top-0 md:-top-12 lg:-top-24">
					<div className="md:flex flex-col gap-2 hidden" style={{ flex: 1, maxHeight: "100%" }}>
						<div
							className={styles.halfImageContainer}
							style={{ width: "100%", height: "50%", position: "relative", borderRadius: 10, overflow: "hidden", marginBottom: 10 }}
						>
							<Image src={GalleryImage1} alt="Gallery Logo1" width="100%" height="100%" layout="responsive" objectFit="cover" />
						</div>
						<div
							className={styles.halfImageContainer}
							style={{ width: "100%", height: "50%", position: "relative", borderRadius: 10, overflow: "hidden" }}
						>
							<Image src={GalleryImage2} alt="Gallery Logo2" width="100%" height="100%" layout="responsive" objectFit="cover" />
						</div>
					</div>

					<div
						className={styles.imageContainer}
						style={{ flex: 1.2, width: "100%", height: "100%", maxHeight: "100% !important", borderRadius: 10, overflow: "hidden" }}
					>
						<Image src={GalleryImage3} alt="Gallery Logo3" width="100%" height="100% !important" layout="responsive" objectFit="cover" />
					</div>

					<div className="md:flex flex-col gap-2 hidden" style={{ flex: 1 }}>
						<div
							className={styles.halfImageContainer}
							style={{ width: "100%", height: "50%", position: "relative", borderRadius: 10, overflow: "hidden", marginBottom: 10 }}
						>
							<Image src={GalleryImage4} alt="Gallery Logo4" width="100%" height="100%" layout="responsive" objectFit="cover" />
						</div>
						<div
							className={styles.halfImageContainer}
							style={{ width: "100%", height: "50%", position: "relative", borderRadius: 10, overflow: "hidden" }}
						>
							<Image src={GalleryImage5} alt="Gallery Logo5" width="100%" height="100%" layout="responsive" objectFit="cover" />
						</div>
					</div>
				</div>
			</div>

			<div className="mt-5 sm:mt-[250px] md:mt-[200px] px-[12%] md:px-[20%]">
				<p className="text-xl text-[#777777] text-left font-thin">Our story</p>
				<p className="my-5 text-3xl md:text-5xl text-left font-thin" style={{ lineHeight: 1.2 }}>
					Handshake infographic mass market crowdfunding iteration.
				</p>
				<p className="text-xl text-left text-[#777777]">
					Conversion angel investor entrepreneur first mover advantage. Handshake infographic mass market crowdfunding iteration. Traction
					stock user experience deployment beta innovator incubator focus. Sales user experience branding growth hacking holy grail
					monetization conversion prototype stock network effects. Learning curve network effects return on investment bootstrapping
					business-to-consumer.{" "}
				</p>
			</div>

			<div className="mt-24 bg-[#0A2640] px-[10%] sm:px-[12%] py-12 sm:py-24">
				<p className="text-2xl text-center text-white font-thin">Our numbers</p>
				<p className="text-xl md:text-5xl font-thin text-center text-white mt-3 mb-20" style={{ lineHeight: 1.5 }}>
					Handshake infographic mass market crowdfunding iteration.
				</p>

				<div className="flex flex-col md:flex-row justify-between">
					<div className="flex flex-col items-center mb-10">
						<div className="text-[#4FE9A4] text-7xl lg:text-8xl font-normal mb-2">120m</div>
						<div className="text-xl font-thin text-white">Cool feature title</div>
					</div>
					<div className="flex flex-col items-center mb-10">
						<div className="text-[#4FE9A4] text-7xl lg:text-8xl font-normal mb-2">10.000</div>
						<div className="text-xl font-thin text-white">Cool feature title</div>
					</div>
					<div className="flex flex-col items-center mb-10">
						<div className="text-[#4FE9A4] text-7xl lg:text-8xl font-normal mb-2">240</div>
						<div className="text-xl font-thin text-white">Cool feature title</div>
					</div>
				</div>
			</div>

			<div className="pb-16 md:pb-40">
				<div className="mt-5 sm:mt-[100px] px-[12%] md:px-[20%]">
					<p className="text-xl text-[#777777] text-left font-thin">Our team</p>
					<p className="my-5 text-3xl md:text-5xl text-left font-thin" style={{ lineHeight: 1.2 }}>
						The leadership team
					</p>
					<p className="text-xl text-left text-[#777777] font-thin">
						Conversion angel investor entrepreneur first mover advantage. Handshake infographic mass market crowdfunding iteration.
						Traction stock user experience deployment beta innovator incubator focus.
					</p>
				</div>

				<div className="flex flex-col md:flex-row gap-12 px-[10%] sm:px-[12%] md:gap-14 mt-16">
					<div className="w-full">
						<div
							className={styles.imageContainer}
							style={{ width: "100%", height: "100%", maxHeight: "100% !important", borderRadius: 10, overflow: "hidden" }}
						>
							<Image src={Team1Img} alt="Gallery Team1" width="100%" height="100% !important" layout="responsive" objectFit="cover" />
						</div>

						<p className="text-xl md:text-[22px] lg:text-2xl mt-6">Michael Scott</p>
						<p className="text-lg md:text-xl text-[#777777]">General Manager</p>
					</div>

					<div className="w-full">
						<div
							className={styles.imageContainer}
							style={{ width: "100%", height: "100%", maxHeight: "100% !important", borderRadius: 10, overflow: "hidden" }}
						>
							<Image src={Team2Img} alt="Gallery Team2" width="100%" height="100% !important" layout="responsive" objectFit="cover" />
						</div>
						<p className="text-xl md:text-[22px] lg:text-2xl mt-6">Dwight Schrute</p>
						<p className="text-lg md:text-xl text-[#777777]">General Manager</p>
					</div>

					<div className="w-full">
						<div
							className={styles.imageContainer}
							style={{ width: "100%", height: "100%", maxHeight: "100% !important", borderRadius: 10, overflow: "hidden" }}
						>
							<Image src={Team3Img} alt="Gallery Team3" width="100%" height="100% !important" layout="responsive" objectFit="cover" />
						</div>
						<p className="text-xl md:text-[22px] lg:text-2xl mt-6">Pam Beetsley</p>
						<p className="text-lg md:text-xl text-[#777777]">General Manager</p>
					</div>
				</div>
			</div>

			<div className="bg-[#0A2640] pt-5 sm:pt-[100px] pb-5 sm:pb-[100px]">
				<div className="px-[12%] md:px-[20%]">
					<p className="text-xl text-white text-left font-thin">Our values</p>
					<p className="my-5 text-3xl md:text-5xl text-left font-thin text-white" style={{ lineHeight: 1.2 }}>
						Things in we believe
					</p>
					<p className="text-xl text-left text-white font-thin">
						Conversion angel investor entrepreneur first mover advantage. Handshake infographic mass market crowdfunding iteration.
						Traction stock user experience deployment beta innovator incubator focus.
					</p>

					<div className="mt-16 flex flex-col md:flex-row gap-12 justify-between">
						<div
							className={styles.imageContainer}
							style={{ width: 150, height: 150, minWidth: 150, maxHeight: "150px !important", borderRadius: 10, overflow: "hidden" }}
						>
							<Image
								src={GalleryImage2}
								alt="Gallery Team2"
								width="100%"
								height="100% !important"
								layout="responsive"
								objectFit="cover"
							/>
						</div>

						<div>
							<p className="text-[28px] text-white font-thin">We are commited.</p>
							<p className="text-xl text-white mt-4 text-left font-thin">
								Conversion angel investor entrepreneur first mover advantage. Handshake infographic mass market crowdfunding
								iteration.{" "}
							</p>
						</div>
					</div>

					<div className="mt-16 flex flex-col md:flex-row gap-12 justify-between">
						<div
							className={styles.imageContainer}
							style={{ width: 150, height: 150, minWidth: 150, maxHeight: "150px !important", borderRadius: 10, overflow: "hidden" }}
						>
							<Image
								src={GalleryImage4}
								alt="Gallery Team4"
								width="100%"
								height="100% !important"
								layout="responsive"
								objectFit="cover"
							/>
						</div>

						<div>
							<p className="text-[28px] text-white font-thin">We are commited.</p>
							<p className="text-xl text-white mt-4 text-left font-thin">
								Conversion angel investor entrepreneur first mover advantage. Handshake infographic mass market crowdfunding
								iteration.{" "}
							</p>
						</div>
					</div>

					<div className="mt-16 flex flex-col md:flex-row gap-12 justify-between">
						<div
							className={styles.imageContainer}
							style={{ width: 150, height: 150, minWidth: 150, maxHeight: "150px !important", borderRadius: 10, overflow: "hidden" }}
						>
							<Image
								src={GalleryImage6}
								alt="Gallery Team6"
								width="100%"
								height="100% !important"
								layout="responsive"
								objectFit="cover"
							/>
						</div>

						<div>
							<p className="text-[28px] text-white font-thin">We are commited.</p>
							<p className="text-xl text-white mt-4 text-left font-thin">
								Conversion angel investor entrepreneur first mover advantage. Handshake infographic mass market crowdfunding
								iteration.{" "}
							</p>
						</div>
					</div>
				</div>
			</div>

			<div className="px-[10%] sm:px-[12%] py-12 md:py-28">
				<div className="py-[72px] bg-[#0A2640] flex flex-col items-center rounded-2xl">
					<p className="text-white text-2xl md:text-5xl font-thin text-center w-2/3" style={{ lineHeight: 1.2 }}>
						An enterprise template to ramp up your company website
					</p>

					<div className="flex flex-col md:flex-row md:gap-6 md:justify-center mt-12">
						<input
							type="text"
							placeholder="Your email address"
							className="rounded-3xl h-12 px-4 md:w-[270px] lg:w-[370px] outline-none"
						/>
						<div className="h-12 mt-4 md:mt-0 px-14 rounded-3xl cursor-pointer bg-[#65e4a3] flex items-center justify-center font-bold">
							Start now
						</div>
					</div>
				</div>
			</div>

			<Footer />
		</div>
	);
}
